version: '3.9'
services:
  db:
    image: ./db
    container_name: homelibrarydb
    build: .
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  api:
    image: home-library-service-db
    container_name: home-library-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - db
    volumes:
      - ./src:/usr/app/src
    restart: always
    environment:
      POSTGRES_HOST: db